/**
 * User Constants
 */
//LOGIN
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//USER REGISTRATION
export const USER_REGISTRATION_START = "USER_REGISTRATION_START";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAILURE = "USER_REGISTRATION_FAILURE";

//USER GET
export const USER_GET_START = "USER_GET_START";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_GET_FAILURE = "USER_GET_FAILURE";

// user transactions get
export const USER_TRANSACTIONS_GET_START = "USER_TRANSACTIONS_GET_START";
export const USER_TRANSACTIONS_GET_SUCCESS = "USER_TRANSACTIONS_GET_SUCCESS";
export const USER_TRANSACTIONS_GET_FAILURE = "USER_TRANSACTIONS_GET_FAILURE";


//USER UPDATE
export const USER_UPDATE_START = "USER_UPDATE_START";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE";

// FORGOT PASSWORD
export const FORGOT_PASSWORD_START = "FORGOT_PASSWORD_START";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

export const LOGOUT = "LOGOUT";

export const SELECTED_USER = "SELECTED_USER";

// GET WALLETS DATA
export const GET_WALLETS_START = "GET_WALLETS_START";
export const GET_WALLETS_SUCCESS = "GET_WALLETS_SUCCESS";
export const GET_WALLETS_FAILURE = "GET_WALLETS_FAILURE";
export const SET_WALLETS_DATA = "SET_WALLETS_DATA";

// ADD WALLETS DATA
export const ADD_WALLETS_START = "ADD_WALLETS_START";
export const ADD_WALLETS_SUCCESS = "ADD_WALLETS_SUCCESS";
export const ADD_WALLETS_FAILURE = "ADD_WALLETS_FAILURE";

// ACCEPT WALLETS DATA
export const ACCEPT_WALLETS_START = "ACCEPT_WALLETS_START";
export const ACCEPT_WALLETS_SUCCESS = "ACCEPT_WALLETS_SUCCESS";
export const ACCEPT_WALLETS_FAILURE = "ACCEPT_WALLETS_FAILURE";


// GET TRANSACTIONS_HISTORY DATA
export const GET_TRANSACTIONS_HISTORY_START = "GET_TRANSACTIONS_HISTORY_START";
export const GET_TRANSACTIONS_HISTORY_SUCCESS = "GET_TRANSACTIONS_HISTORY_SUCCESS";
export const GET_TRANSACTIONS_HISTORY_FAILURE = "GET_TRANSACTIONS_HISTORY_FAILURE";
export const SET_TRANSACTIONS_HISTORY_DATA = "SET_TRANSACTIONS_HISTORY_DATA";

// GAMES DATA
export const GET_GAMES_START = "GET_GAMES_START";
export const GET_GAMES_SUCCESS = "GET_GAMES_SUCCESS";
export const GET_GAMES_FAILURE = "GET_GAMES_FAILURE";

export const ADD_GAMES_START = "ADD_GAMES_START";
export const ADD_GAMES_SUCCESS = "ADD_GAMES_SUCCESS";
export const ADD_GAMES_FAILURE = "ADD_GAMES_FAILURE";

// GAME_BETS DATA
export const GET_GAME_BETS_START = "GET_GAME_BETS_START";
export const GET_GAME_BETS_SUCCESS = "GET_GAME_BETS_SUCCESS";
export const GET_GAME_BETS_FAILURE = "GET_GAME_BETS_FAILURE";

export const ADD_GAME_BETS_START = "ADD_GAME_BETS_START";
export const ADD_GAME_BETS_SUCCESS = "ADD_GAME_BETS_SUCCESS";
export const ADD_GAME_BETS_FAILURE = "ADD_GAME_BETS_FAILURE";

export const UPDATE_GAME_BETS_START = "UPDATE_GAME_BETS_START";
export const UPDATE_GAME_BETS_SUCCESS = "UPDATE_GAME_BETS_SUCCESS";
export const UPDATE_GAME_BETS_FAILURE = "UPDATE_GAME_BETS_FAILURE";

// GET SHORT_LIST_USER DATA
export const GET_SHORT_LIST_USER_START = "GET_SHORT_LIST_USER_START";
export const GET_SHORT_LIST_USER_SUCCESS = "GET_SHORT_LIST_USER_SUCCESS";
export const GET_SHORT_LIST_USER_FAILURE = "GET_SHORT_LIST_USER_FAILURE";

// ADD SHORT_LIST_USER DATA
export const ADD_SHORT_LIST_USER_START = "ADD_SHORT_LIST_USER_START";
export const ADD_SHORT_LIST_USER_SUCCESS = "ADD_SHORT_LIST_USER_SUCCESS";
export const ADD_SHORT_LIST_USER_FAILURE = "ADD_SHORT_LIST_USER_FAILURE";

// ADD SHORT_LIST_USER DATA
export const REMOVE_SHORT_LIST_USER_START = "REMOVE_SHORT_LIST_USER_START";
export const REMOVE_SHORT_LIST_USER_SUCCESS = "REMOVE_SHORT_LIST_USER_SUCCESS";
export const REMOVE_SHORT_LIST_USER_FAILURE = "REMOVE_SHORT_LIST_USER_FAILURE";

// GET MESSAGES
export const GET_MESSAGES_LIST_START = "GET_MESSAGES_LIST_START";
export const GET_MESSAGES_LIST_SUCCESS = "GET_MESSAGES_LIST_SUCCESS";
export const GET_MESSAGES_LIST_FAILURE = "GET_MESSAGES_LIST_FAILURE";

// ADD MESSAGES
export const ADD_MESSAGES_LIST_START = "ADD_MESSAGES_LIST_START";
export const ADD_MESSAGES_LIST_SUCCESS = "ADD_MESSAGES_LIST_SUCCESS";
export const ADD_MESSAGES_LIST_FAILURE = "ADD_MESSAGES_LIST_FAILURE";

// GET PRICING PLANS
export const GET_PLANS_LIST_START = "GET_PLANS_LIST_START";
export const GET_PLANS_LIST_SUCCESS = "GET_PLANS_LIST_SUCCESS";
export const GET_PLANS_LIST_FAILURE = "GET_PLANS_LIST_FAILURE";
export const SET_PLAN_DETAIL = "SET_PLAN_DETAIL";